Update

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,6 +28,24 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Infer record ID
+      id: infer-record-id
+      run: |
+        if [[ -z "${{ inputs.record-id }}" ]]; then
+          if [[ -f "${{ github.action_path }}/starlite.manifest.json" ]]; then
+            RECORD_ID=$(grep -o '"id"[[:space:]]*:[[:space:]]*".*"' "${{ github.action_path }}/starlite.manifest.json" | awk -F':' '{gsub(/[", ]/, "", $2); print $2}')
+          fi
+
+          if [[ -z "$RECORD_ID" ]]; then
+            echo "❌ ERROR: RECORD_ID is not set and could not be inferred from the manifest file!" >&2
+            exit 1
+          fi
+
+          echo "record-id=$RECORD_ID" >> "$GITHUB_ENV"
+        else
+          echo "record-id=${{ inputs.record-id }}" >> "$GITHUB_ENV"
+        fi
+
     - name: Update record
       if: ${{ inputs.run-record == 'true' }}
       run: ${{ github.action_path }}/starlite.sh --org-id ${{ inputs.org-id }} --record-id ${{ inputs.record-id }} --token ${{ inputs.api-key }} --action "record"
